[package]
name = "fisk"
version = "0.1.0"
authors = ["Aksel Slettemark <akselslettemark@gmail.com>"]
edition = "2018"

[dependencies]
bitintr = "0.3.0"
lazy_static = "1.4.0"
clap = "2.33.3"
time = "0.1.44"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
# debug = true
panic = "abort"
